package GUI;

import BUS.LoaiNhacCuBUS;
import BUS.NhacCuBUS;
import DAO.NhacCuDAO;
import DTO.LoaiNhacCuDTO;
import DTO.NhacCuDTO;
import anlavn.ui.Mode;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class NhacCuGUI extends JPanel implements KeyListener {


    public NhacCuGUI() {
        initComponents();
        this.setSize(1090, 750);
        getListCombobox();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        pThongKe = new javax.swing.JPanel();
        lbGiaMin = new javax.swing.JLabel();
        TongLoaiSoSach = new javax.swing.JLabel();
        txtTongLNC = new javax.swing.JTextField();
        txtGiaMin = new javax.swing.JTextField();
        TongSoSach = new javax.swing.JLabel();
        txtTongNC = new javax.swing.JTextField();
        lbGiaMax = new javax.swing.JLabel();
        txtGiaMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pInput = new javax.swing.JPanel();
        lbMaSach = new javax.swing.JLabel();
        lbMaNXB = new javax.swing.JLabel();
        lbMaTL = new javax.swing.JLabel();
        lbTenSach = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        cbbHang = new javax.swing.JComboBox<>();
        txtTenNC = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtTongSL = new javax.swing.JTextField();
        lnNamXuatBan = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        cbbLNC = new javax.swing.JComboBox<>();
        txtMaNC = new javax.swing.JTextField();
        pButton = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btChonAnh = new javax.swing.JButton();
        btHienThiTatCa = new javax.swing.JButton();
        pSearch = new javax.swing.JPanel();
        lbSearchMaSach = new javax.swing.JLabel();
        lbSearchMaNXB = new javax.swing.JLabel();
        lbSearchTenSach = new javax.swing.JLabel();
        txtSearchTenNC = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        cbbSearchHang = new javax.swing.JComboBox<>();
        lbSearchMATL = new javax.swing.JLabel();
        lbMin = new javax.swing.JLabel();
        txtSearchMin = new javax.swing.JTextField();
        lbMax = new javax.swing.JLabel();
        txtSearchMax = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbbSearchLNC = new javax.swing.JComboBox<>();
        txtSearchMaNC = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhacCu = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        pThongKe.setBackground(new java.awt.Color(255, 255, 255));

        lbGiaMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMin.setText("GIÁ THẤP NHẤT:");

        TongLoaiSoSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongLoaiSoSach.setText("SỐ LOẠI NHẠC CỤ:");

        TongSoSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongSoSach.setText("TỔNG SỐ NHẠC CỤ:");

        lbGiaMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMax.setText("GIÁ CAO NHẤT:");

        javax.swing.GroupLayout pThongKeLayout = new javax.swing.GroupLayout(pThongKe);
        pThongKe.setLayout(pThongKeLayout);
        pThongKeLayout.setHorizontalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongKeLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGiaMin)
                    .addComponent(TongLoaiSoSach, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongLNC, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txtGiaMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGiaMax)
                    .addComponent(TongSoSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongNC, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txtGiaMax)))
        );
        pThongKeLayout.setVerticalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongKeLayout.createSequentialGroup()
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongNC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongLNC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TongLoaiSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ NHẠC CỤ");

        pInput.setBackground(new java.awt.Color(255, 255, 255));

        lbMaSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaSach.setText("MÃ NHẠC CỤ:");

        lbMaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaNXB.setText("LOẠI NHẠC CỤ");

        lbMaTL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTL.setText("HÃNG:");

        lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenSach.setText("TÊN  NHẠC CỤ:");

        lbSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSoLuong.setText("GIÁ BÁN:");

        lbDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDonGia.setText("SỐ LƯỢNG:");

        cbbHang.setBackground(new java.awt.Color(243, 238, 238));
        cbbHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTenNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtGiaBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTongSL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lnNamXuatBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnNamXuatBan.setText("GIÁ NHẬP:");

        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbbLNC.setBackground(new java.awt.Color(243, 238, 238));
        cbbLNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout pInputLayout = new javax.swing.GroupLayout(pInput);
        pInput.setLayout(pInputLayout);
        pInputLayout.setHorizontalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNC, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongSL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaTL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbHang, 0, 223, Short.MAX_VALUE)
                            .addComponent(cbbLNC, 0, 223, Short.MAX_VALUE)
                            .addComponent(txtMaNC)))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addComponent(lnNamXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        anlavn.net.License.check("alk~TYmqkzOTN93bzxn2rf6rSbhmto+k9V5GppStoJmlUFAej2UDu/c9jomeq0gOfKLcbL9wSkFUOLDLC67STg2FDkOVThuS+L3zKWSkLLDDFdI=");
        pInputLayout.setVerticalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtMaNC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLNC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pButton.setBackground(new java.awt.Color(255, 255, 255));
        pButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdd_150px.png"))); // NOI18N
        btThem.setBorder(null);
        btThem.setContentAreaFilled(false);
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.setPreferredSize(new java.awt.Dimension(200, 43));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 0, 0));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEdit_150px.png"))); // NOI18N
        btSua.setBorder(null);
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.setPreferredSize(new java.awt.Dimension(57, 31));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDelete_150px.png"))); // NOI18N
        btXoa.setBorder(null);
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btChonAnh.setBackground(new java.awt.Color(102, 102, 255));
        btChonAnh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btChonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_opened_folder_30px.png"))); // NOI18N
        btChonAnh.setText("CHỌN ẢNH");
        btChonAnh.setBorder(null);
        btChonAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonAnhActionPerformed(evt);
            }
        });

        btHienThiTatCa.setBackground(new java.awt.Color(0, 153, 0));
        btHienThiTatCa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHienThiTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btHienThiTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        btHienThiTatCa.setText("LÀM MỚI");
        btHienThiTatCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHienThiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButtonLayout = new javax.swing.GroupLayout(pButton);
        pButton.setLayout(pButtonLayout);
        pButtonLayout.setHorizontalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        pButtonLayout.setVerticalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pSearch.setBackground(new java.awt.Color(255, 255, 255));
        pSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        lbSearchMaSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMaSach.setText("MÃ NC");

        lbSearchMaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMaNXB.setText("LOẠI NC");

        lbSearchTenSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchTenSach.setText("TÊN NC:");

        txtSearchTenNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btTimKiem.setBackground(new java.awt.Color(204, 204, 204));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_25px_focus.png"))); // NOI18N
        btTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        cbbSearchHang.addItem("Không");
        cbbSearchHang.setBackground(new java.awt.Color(243, 238, 238));
        cbbSearchHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbSearchHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không" }));

        lbSearchMATL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMATL.setText("HÃNG:");

        lbMin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMin.setText(" TỪ:");

        txtSearchMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMax.setText("ĐẾN:");

        txtSearchMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("KHOẢNG GIÁ");

        cbbSearchLNC.addItem("Không");
        cbbSearchLNC.setBackground(new java.awt.Color(243, 238, 238));
        cbbSearchLNC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbbSearchLNC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không" }));

        javax.swing.GroupLayout pSearchLayout = new javax.swing.GroupLayout(pSearch);
        pSearch.setLayout(pSearchLayout);
        pSearchLayout.setHorizontalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchMaNXB)
                        .addGap(14, 14, 14)
                        .addComponent(cbbSearchLNC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchMaSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMaNC, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbSearchMATL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSearchTenSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbSearchHang, 0, 200, Short.MAX_VALUE)
                    .addComponent(txtSearchTenNC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSearchLayout.createSequentialGroup()
                        .addComponent(lbMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSearchLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(137, 137, 137)))
                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pSearchLayout.setVerticalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSearchMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchTenNC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchMaNC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSearchMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchMATL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSearchHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSearchLNC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btTimKiem))
                .addGap(7, 7, 7))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblHinh.setBackground(new java.awt.Color(102, 255, 102));
        lblHinh.setForeground(new java.awt.Color(153, 153, 153));
        lblHinh.setToolTipText("");
        lblHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        lblHinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblNhacCu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(102, 102, 102)));
        tblNhacCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhacCu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhạc cụ", "Loại nhạc cụ", "Tên nhạc cụ", "Hãng", "Hình", "Giá nhập", "Giá bán", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhacCu.setGridColor(new java.awt.Color(102, 102, 102));
        tblNhacCu.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblNhacCu.setShowGrid(true);
        tblNhacCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhacCuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhacCu);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 111, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(pButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(38, 38, 38))
                        .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        try {
            int eff = NhacCuBUS.insert(getView());
            if(eff == 0) throw new RuntimeException();
            cleanView();
            fillTable();
        } catch (RuntimeException | SQLException ex) {
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to insert NhacCu");
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        try {
            int eff = NhacCuBUS.update(getView());
            if(eff == 0) throw new RuntimeException();
            cleanView();
            fillTable();
        } catch (RuntimeException | SQLException ex) {
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to update NhacCu");
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        try {
            if(Mode.WConfirm(this, "Are you sure to delete this NhacCu") != JOptionPane.YES_OPTION) return;
            int eff = NhacCuBUS.delete(getView().getMaNC());
            if(eff == 0) throw new RuntimeException();
            cleanView();
            fillTable();
        } catch (RuntimeException | SQLException ex) {
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to delete NhacCu");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonAnhActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG imgs", "jpg", "png");
        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile();
                System.out.println(file.getAbsolutePath());
                this.imgFile = file.getCanonicalPath();
                lblHinh.setIcon(new ImageIcon(ImageIO.read(file).getScaledInstance(200, 230, Image.SCALE_DEFAULT)));
                repaint();
            } catch (IOException ex) {
                Logger.getLogger(NhacCuGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btChonAnhActionPerformed

    private void btHienThiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiTatCaActionPerformed
        cleanView();
        fillTable();
    }//GEN-LAST:event_btHienThiTatCaActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        try {
            searchBy();
        }catch(SQLException ex){
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to search NhacCu");
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void tblNhacCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhacCuMouseClicked
        viewDetail();
    }//GEN-LAST:event_tblNhacCuMouseClicked

    

    private String imgFile = null;
    private DefaultTableModel model;
    List<LoaiNhacCuDTO> listLNC = new ArrayList<>();
    List<String> listHang = Arrays.asList("Yamaha", "KORG", "Kawai", "Young Chang", "Roland", "Enya Group Music", "Cort", "Sqoe", "Joyo", "KHALY", "FULLY", "NISSI", "Gecko", "Alto", "Takstar", "Mackie", "Samson", "PreSonus");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel TongLoaiSoSach;
    private javax.swing.JLabel TongSoSach;
    private javax.swing.JButton btChonAnh;
    private javax.swing.JButton btHienThiTatCa;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbbHang;
    private javax.swing.JComboBox<String> cbbLNC;
    private javax.swing.JComboBox<String> cbbSearchHang;
    private javax.swing.JComboBox<String> cbbSearchLNC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbGiaMax;
    private javax.swing.JLabel lbGiaMin;
    private javax.swing.JLabel lbMaNXB;
    private javax.swing.JLabel lbMaSach;
    private javax.swing.JLabel lbMaTL;
    private javax.swing.JLabel lbMax;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbSearchMATL;
    private javax.swing.JLabel lbSearchMaNXB;
    private javax.swing.JLabel lbSearchMaSach;
    private javax.swing.JLabel lbSearchTenSach;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lnNamXuatBan;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pSearch;
    private javax.swing.JPanel pThongKe;
    private javax.swing.JTable tblNhacCu;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaMax;
    private javax.swing.JTextField txtGiaMin;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaNC;
    private javax.swing.JTextField txtSearchMaNC;
    private javax.swing.JTextField txtSearchMax;
    private javax.swing.JTextField txtSearchMin;
    private javax.swing.JTextField txtSearchTenNC;
    private javax.swing.JTextField txtTenNC;
    private javax.swing.JTextField txtTongLNC;
    private javax.swing.JTextField txtTongNC;
    private javax.swing.JTextField txtTongSL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private void getListCombobox() {
        try {
            listLNC = LoaiNhacCuBUS.select();
            for (LoaiNhacCuDTO nc : listLNC) {
                cbbLNC.addItem(nc.getTenLNC());
                cbbSearchLNC.addItem(nc.getTenLNC());
            }
            for (String hang : listHang) {
                cbbHang.addItem(hang);
                cbbSearchHang.addItem(hang);
            }
        } catch (SQLException ex) {
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to query NhacCu");
        }
    }

    private void fillTable() {
        try {
            fillTable(NhacCuBUS.select());
        } catch (SQLException ex) {
            System.err.println(ex.toString());
            Mode.WMessage(this, "Error try to query NhacCu");
        }
    }

    private void fillTable(List<NhacCuDTO> list) {
        model = (DefaultTableModel) tblNhacCu.getModel();
        model.setRowCount(0);
        double min = list.get(0).getGiaBan(), max = 0;
        for (NhacCuDTO e : list) {
            final String loaiNC = listLNC.stream().filter(lnc -> lnc.getMaLNC().equals(e.getMaLNC())).map(LoaiNhacCuDTO::getTenLNC).findFirst().orElse("None");
            final double giaBan = e.getGiaBan();
            model.addRow(new Object[]{e.getMaNC(), loaiNC, e.getTenNC(), e.getHang(), e.getHinh(), String.format("%.0f", e.getGiaNhap()), String.format("%.0f", giaBan), e.getTongSL()});
            min = giaBan < min ? giaBan : min;
            max = giaBan > max ? giaBan : max;
        }
        
        txtGiaMin.setText(String.format("%.0f", min));
        txtGiaMax.setText(String.format("%.0f", max));
        txtTongLNC.setText(String.valueOf(listLNC.size()));
        txtTongNC.setText(String.valueOf(list.size()));
        tblNhacCu.setModel(model);
    }

    private void viewDetail() {
        final int i = tblNhacCu.getSelectedRow();
        final String tenLNC = model.getValueAt(i,1).toString();
        final String hinhPath = model.getValueAt(i, 4) != null ? model.getValueAt(i, 4).toString() : null;
        txtMaNC.setText(model.getValueAt(i,0).toString());
        for(int j = 0 ; j < listLNC.size()-1 ; j++){
            if(listLNC.get(j).getTenLNC().equals(tenLNC)) cbbLNC.setSelectedIndex(j);
        }
        txtTenNC.setText(model.getValueAt(i,2).toString());
        cbbHang.setSelectedItem(model.getValueAt(i,3).toString());
        txtGiaNhap.setText(model.getValueAt(i,5).toString());
        txtGiaBan.setText(model.getValueAt(i,6).toString());
        txtTongSL.setText(model.getValueAt(i,7).toString());
        
        Image hinh = null;
        imgFile = hinhPath;
        try {
            hinh = new ImageIcon(hinhPath).getImage().getScaledInstance(92, 105, Image.SCALE_DEFAULT);
        } catch (Exception E) {
            hinh = new ImageIcon("./src/img/SanPham/NoImage.jpg").getImage().getScaledInstance(92, 105, Image.SCALE_DEFAULT);
        }
        lblHinh.setIcon(new ImageIcon(hinh));
    }

    private NhacCuDTO getView() {
        NhacCuDTO nc = new NhacCuDTO();
        nc.setMaNC(txtMaNC.getText().trim());
        nc.setMaLNC(listLNC.get(cbbLNC.getSelectedIndex()).getMaLNC());
        nc.setHang(listHang.get(cbbHang.getSelectedIndex()));
        nc.setHinh(imgFile);
        nc.setTenNC(txtTenNC.getText().trim());
        nc.setGiaNhap(Double.valueOf(txtGiaNhap.getText().trim()));
        nc.setGiaBan(Double.valueOf(txtGiaBan.getText().trim()));
        nc.setTongSL(Integer.valueOf(txtTongSL.getText().trim()));
        return nc;
    }
    
    private void cleanView(){
        txtMaNC.setText("");
        cbbLNC.setSelectedIndex(-1);
        cbbHang.setSelectedIndex(-1);
        txtTenNC.setText("");
        txtGiaNhap.setText("0");
        txtGiaBan.setText("0");
        txtTongSL.setText("0");
        lblHinh.setIcon(null);
        imgFile = null;
    }
    
    private void searchBy() throws SQLException{
        final int lnc = cbbSearchLNC.getSelectedIndex(),
                 hang = cbbSearchHang.getSelectedIndex();
        final String maNC = txtSearchMaNC.getText().trim(),
                    tenNC = txtSearchTenNC.getText().trim(),
                    maLNC = lnc > 0 ? listLNC.get(lnc - 1).getMaLNC() : null,
                  tenHang = hang > 0 ? listHang.get(hang - 1) : null,
                    mint = txtSearchMin.getText().trim(),
                    maxt = txtSearchMax.getText().trim();
        
        if(maNC.isBlank() && tenNC.isBlank() && maLNC == null && tenHang == null && mint.isBlank() && maxt.isBlank()) {fillTable(); return;}
        
        final double min = !mint.isBlank() ? Double.valueOf(mint): 0, max = !maxt.isBlank() ? Double.valueOf(maxt) : 0;
        String query = "SELECT * FROM NHACCU WHERE ";
        List<Object> args = new ArrayList<>();
        if(!maNC.isBlank()) {query += "LOWER(MANC) LIKE LOWER(?) AND "; args.add("%"+maNC+"%");}
        if(!tenNC.isBlank()){query += "LOWER(TENNC) LIKE LOWER(?) AND ";args.add("%"+tenNC+"%");}
        if(maLNC != null)   {query += "MALNC = ? AND "; args.add(maLNC);}
        if(tenHang != null) {query += "HANG = ? AND "; args.add(tenHang);}
        if(min>0 && max>0)  {query += "GIABAN BETWEEN ? AND ?";args.add(min);args.add(max);}
        if(query.endsWith("AND ")) query = query.substring(0, query.length() - 5);
        fillTable(NhacCuDAO.query(query, args.toArray()));
    }
}
